name: Go Tests
on:
  push:
    branches: [ main, master ]
  pull_request:
    branches: [ main, master ]
  workflow_dispatch:
jobs:
  test:
    timeout-minutes: 60
    runs-on: ubuntu-latest
    container:
      image: postgres
    steps:
    - uses: actions/checkout@v4
    - name: Setup environment variabels
      env:
        TESTING_ENV_FILE: ${{ secrets.QA_ENV_FILE }}
      run: |
        echo "$TESTING_ENV_FILE" > .env
        cat .env

    - name: Install build essentials
      run: |
        apt-get update && \
        apt-get install -y build-essential

    - name: Install Docker
      run: |
        apt-get update -y
        apt-get install -y \
          apt-transport-https \
          ca-certificates \
          curl \
          software-properties-common

        curl -fsSL https://download.docker.com/linux/debian/gpg | apt-key add -

       
        echo "deb [arch=amd64] https://download.docker.com/linux/debian $(lsb_release -cs) stable" | tee /etc/apt/sources.list.d/docker.list

  
        apt-get update -y
        apt-get install -y docker-ce

    - name: Run Makefile
      run: |
        docker --version
        make create_container
        make start_container
        sleep 10
        make create_db
        make migrate_up

    - uses: actions/setup-go@v5
      with:
        go-version: 'stable'
    - name: Run tests
      run: |
          go install github.com/onsi/ginkgo/v2/ginkgo
          go get github.com/onsi/gomega/...
          go mod tidy
          ginkgo -r -cover
