name: Playwright Tests
on:
  push:
    branches: [ main, master ]
  pull_request:
    branches: [ main, master ]
  workflow_dispatch:
jobs:
  test:
    timeout-minutes: 60
    runs-on: ubuntu-latest
    container:
      image: postgres
    steps:
    - uses: actions/checkout@v4
    - name: Setup env
      run: echo $QA_ENV_FILE | base64 --decode > .env
    - name: Echo env
      run: | 
        sudo apt-get update
        sudo apt-get install build-essential
        make create_container
