name: Go Tests
on:
  push:
    branches: [ main, master ]
  pull_request:
    branches: [ main, master ]
  workflow_dispatch:
jobs:
  test:
    timeout-minutes: 60
    runs-on: ubuntu-latest
    container:
      image: postgres
    steps:
    - uses: actions/checkout@v4
    - name: Setup environment variabels
      env:
        TESTING_ENV_FILE: ${{ secrets.QA_ENV_FILE }}
      run: |
        echo "$TESTING_ENV_FILE" > .env
        cat .env

    - name: Install build essentials
      run: |
        apt-get update && \
        apt-get install -y build-essential

    - name: Install Docker
      run: |
        apt-get update -y
        apt-get install -y \
          apt-transport-https \
          ca-certificates \
          curl \
          software-properties-common

        curl -fsSL https://download.docker.com/linux/debian/gpg | apt-key add -

       
        echo "deb [arch=amd64] https://download.docker.com/linux/debian $(lsb_release -cs) stable" | tee /etc/apt/sources.list.d/docker.list

  
        apt-get update -y
        apt-get install -y docker-ce

    - name: Setup open ssl
      run: | 
        apt-get install -y pkg-config libssl-dev
        export PKG_CONFIG_ALLOW_SYSTEM_CFLAGS=1
        export PKG_CONFIG_PATH=/usr/lib/x86_64-linux-gnu/pkgconfig

    - uses: actions/setup-go@v5
      with:
        go-version: 'stable'
    - uses: actions-rs/toolchain@v1
      with:
        toolchain: stable

    - name: Install Dependencies
      run: |
        cargo install sqlx-cli --no-default-features --features native-tls,postgres
        go mod tidy          # Ensure dependencies are tidy
        go install github.com/onsi/ginkgo/v2/ginkgo
        go get github.com/onsi/gomega/...

    - name: Run Makefile
      run: |
        make create_container
        make start_container
        sleep 10
        make create_db
        sleep 10
        until docker exec coffee-container pg_isready --username=root --dbname=coffee --host=localhost; do
          echo "Waiting for PostgreSQL..."
          sleep 2
        done
        docker logs coffee-container
        make migrate_up


    - name: Run tests
      run: ginkgo -r -cover
