name: Go Tests
on:
  push:
    branches: [ main, master ]
  pull_request:
    branches: [ main, master ]
  workflow_dispatch:
jobs:
  test:
    timeout-minutes: 60
    runs-on: ubuntu-latest
    container:
      image: postgres
    steps:
    - uses: actions/checkout@v4
    - name: Setup environment variabels
      run: echo $QA_ENV_FILE | base64 --decode > .env

    - name: Install build essentials
      run: |
        apt-get update && \
        apt-get install -y build-essential

    - name: Run Makefile
      run: make create_container